TITLES = [
    "Novice Squire",
    "Apprentice Knight",
    "Holy Defender",
    "Shieldbearer",
    "Guardian",
    "Crusader",
    "Illuminator",
    "Protector",
    "Champion",
    "Knight Adept",
    "Vindicator",
    "Holy Master",
    "Divine Savant",
    "Paladin",
    "Expert Crusader",
    "Master of Arms",
    "Holy Manipulator",
    "Virtuous Defender",
    "Sanctification Expert",
    "Elite Guardian",
    "Holy Architect",
    "Virtuous Maestro",
    "Sanctification Master",
    "Supreme Guardian",
    "Grandmaster Paladin",
    "Holy Overlord",
    "Sanctification Sage",
    "Quantum Knight",
    "Nano Paladin",
    "Eternal Guardian",
    "Galactic Overlord",
    "Universal Knight",
    "Multiversal Paladin",
    "Cosmic Master",
    "Infinite Guardian",
    "Omniversal Knight",
    "Omniform Paladin",
    "Omnipresent Master",
    "Omnipotent Paladin",
    "Omniscient Knight",
    "Omnipresent Paladin",
    "Omnipotent Master",
    "Omniscient Paladin",
]
