"""
Prototypes
"""

UndeadPawn = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "an undead pawn",
    "aliases": ["undead", "pawn"],
    "tags": ["undead", "chessboard"],
    "desc": "The pawn looks like it has been dead for a long time, its flesh rotting and its eyes glowing with an eerie light.",
    "gender": "neutral",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "energyac": 0,
    "natural_weapon": {
        "name": "claws",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 800,
    "can_attack": True,
}

UndeadRook = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "an undead pawn",
    "aliases": ["undead", "pawn"],
    "tags": ["undead", "chessboard"],
    "desc": "The rook is a massive, hulking figure, its body covered in rotting flesh and its eyes glowing with an eerie light.",
    "gender": "neutral",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "energyac": 0,
    "natural_weapon": {
        "name": "claws",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1000,
    "can_attack": True,
}

UndeadBishop = {
    "key": "an undead bishop",
    "aliases": ["undead", "bishop"],
    "tags": ["undead", "chessboard"],
    "desc": "The bishop is a tall, gaunt figure, its body covered in rotting flesh and its eyes glowing with an eerie light.",
    "gender": "neutral",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "energyac": 0,
    "natural_weapon": {
        "name": "claws",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1050,
    "can_attack": True,
}

UndeadKnight = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "an undead knight",
    "aliases": ["undead", "knight"],
    "tags": ["undead", "chessboard"],
    "desc": "The knight is a tall, imposing figure. He wears a suit of rusted armor and wields a massive sword.",
    "gender": "neutral",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "energyac": 0,
    "natural_weapon": {
        "name": "claws",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1100,
    "can_attack": True,
}

UndeadQueen = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "an undead queen",
    "aliases": ["undead", "queen"],
    "tags": ["undead", "chessboard"],
    "desc": "The undead queen wears a crown of bones and her eyes glow with an eerie light. She wield a scepter made of bone.",
    "gender": "female",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "energyac": 0,
    "natural_weapon": {
        "name": "scepter",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 6,
    "exp_reward": 1200,
    "can_attack": True,
}

UndeadKing = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "an undead king",
    "aliases": ["undead", "king"],
    "tags": ["undead", "chessboard"],
    "desc": "The undead king wears a pointy crown and his eyes glow with an eerie light. He wields a massive sword and wears robes that must have been regal in life.",
    "gender": "male",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "energyac": 0,
    "natural_weapon": {
        "name": "scepter",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 8,
    "exp_reward": 1200,
    "can_attack": True,
}

GnomePawn = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a gnome pawn",
    "aliases": ["gnome", "pawn"],
    "tags": ["gnome", "chessboard"],
    "desc": "The gnome pawn is a small, wiry figure, his eyes sharp and his movements quick and precise.",
    "gender": "male",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "natural_weapon": {
        "name": "dagger",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 800,
    "can_attack": True,
}

DwarfRook = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a dwarf rook",
    "aliases": ["dwarf", "rook"],
    "tags": ["dwarf", "chessboard"],
    "desc": "The dwarf rook is a massive, hulking figure, his beard braided and his eyes sharp.",
    "gender": "male",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "natural_weapon": {
        "name": "axe",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1000,
    "can_attack": True,
}

HighElfKnight = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a high elf knight",
    "aliases": ["high elf", "knight"],
    "tags": ["high elf", "chessboard"],
    "desc": "The high elf knight is a tall, slender figure, his eyes sharp and his movements graceful and precise.",
    "gender": "male",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "natural_weapon": {
        "name": "axe",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1100,
    "can_attack": True,
}

WoodElfQueen = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a wood elf queen",
    "aliases": ["wood elf", "queen"],
    "tags": ["wood elf", "chessboard"],
    "desc": "The wood elf queen is a tall, slender figure, her eyes sharp and her movements graceful and precise.",
    "gender": "male",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "natural_weapon": {
        "name": "axe",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1200,
    "can_attack": True,
}

HighElfKing = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a high elf king",
    "aliases": ["high elf", "king"],
    "tags": ["high elf", "chessboard"],
    "desc": "The high elf king is a tall, slender figure, his eyes sharp and his movements graceful and precise.",
    "gender": "male",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "natural_weapon": {
        "name": "axe",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1300,
    "can_attack": True,
}


WoodElfBishop = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a wood elf bishop",
    "aliases": ["wood elf", "bishop"],
    "tags": ["wood elf", "chessboard"],
    "desc": "The wood elf bishop is a tall, slender figure, his eyes sharp and his movements graceful.",
    "gender": "male",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "natural_weapon": {
        "name": "longsword",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 1050,
    "can_attack": True,
}


SCRAWNY_GNOLL = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a scrawny gnoll",
    "aliases": ["gnoll"],
    "tags": ["gnoll"],
    "desc": "The gnoll stands about five feet tall, and is wearing a torn blue shirt with greenish yellow pants.",
    "gender": "neutral",
    "react_as": "aggressive",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "energyac": 0,
    "natural_weapon": {
        "name": "claws",
        "damage_type": "edged",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "level": 5,
    "exp_reward": 600,
    "can_attack": True,
}

GNOLL_PUP = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a gnoll pup",
    "aliases": ["gnoll", "pup"],
    "desc": "The gnoll stands about three feet tall, and is wearing a torn blue shirt with greenish yellow pants.",
    "gender": "neutral",
    "react_as": "aggressive",
    "armor": 2,
    "name_color": "r",
    "hp": 100,
    "hpmax": 100,
    "str": 10,
    "natural_weapon": {
        "name": "claws",
        "damage_type": "edged",
        "damage": 5,
        "speed": 4,
        "energy_cost": 10,
    },
    "level": 5,
    "exp_reward": 400,
    "can_attack": True,
}


DECAYING_SKELETON = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "a decaying skeleton",
    "aliases": ["skeleton"],
    "desc": "The decaying skeleton cackles as soon as it sees you.",
    "gender": "neutral",
    "react_as": "aggressive",
    "armor": 2,
    "name_color": "r",
    "hp": 100,
    "hpmax": 100,
    "str": 15,
    "natural_weapon": {
        "name": "dagger",
        "damage_type": "edged",
        "damage": 5,
        "speed": 2,
        "energy_cost": 5,
    },
    "level": 5,
    "exp_reward": 400,
    "can_attack": True,
}
