"""
Prototypes
"""

from random import randint, uniform, choice

Markiplier = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Markiplier",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Markiplier himself stands here, ready to guide or challenge those who enter.",
    "gender": "neutral",
    "react_as": "",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 9000,
    "can_attack": True,
}

PewDiePie = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "PewDiePie",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "PewDiePie, the king of YouTube, sits upon it, his signature brofist emblem glowing behind him.",
    "gender": "neutral",
    "react_as": "",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 9500,
    "can_attack": True,
}

MrBeast = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Mr Beast",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Mr Beast stands at the entrance, offering challenges and rewards to those brave enough to participate.",
    "gender": "neutral",
    "react_as": "",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 15000,
    "can_attack": True,
}

Ninja = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Ninja",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Ninja, the master of Fortnite, stands ready for battle, his blue hair glowing under the lights.",
    "gender": "neutral",
    "react_as": "",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 11000,
    "can_attack": True,
}

MatPat = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "MatPat",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "MatPat, the mastermind behind Game Theory, is here, surrounded by clues and puzzles.",
    "gender": "neutral",
    "react_as": "",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 10000,
    "can_attack": True,
}

Wendigoon = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Wendigoon",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Wendigoon is here, talking for hours about random topics of interest at the moment.",
    "gender": "neutral",
    "react_as": "",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 8000,
    "can_attack": True,
}

MeiMei = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Mei Mei",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Mei Mei, the boba influencer is here, pounding bubble tea and ready to chat.",
    "gender": "neutral",
    "react_as": "",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 8000,
    "can_attack": True,
}

Caseoh = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Caseoh",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Caseoh stands at the entrance, offering challenges and rewards to those brave enough to participate.",
    "gender": "neutral",
    "react_as": "friendly",
    "armor": 5,
    "name_color": "r",
    "str": 15,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 20,
        "speed": 4,
        "energy_cost": 1,
    },
    "exp_reward": 10650,
    "can_attack": True,
}

Jacksepticeye = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Jacksepticeye",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Jacksepticeye, the energetic Irish gamer, brings his high spirits and loud greetings.",
    "gender": "neutral",
    "react_as": "friendly",
    "armor": 4,
    "name_color": "g",
    "str": 17,
    "level": 8,
    "natural_weapon": {
        "name": "headbutt",
        "damage_type": "blunt",
        "damage": 24,
        "speed": 4,
        "energy_cost": 2,
    },
    "exp_reward": 9000,
    "can_attack": True,
}

LoganPaul = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Logan Paul",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Logan Paul, the controversial vlogger, is here, his camera always rolling.",
    "gender": "neutral",
    "react_as": "hostile",
    "armor": 6,
    "name_color": "r",
    "str": 18,
    "level": 8,
    "natural_weapon": {
        "name": "punch",
        "damage_type": "blunt",
        "damage": 26,
        "speed": 4,
        "energy_cost": 2,
    },
    "exp_reward": 14000,
    "can_attack": True,
}

BadEmpanada = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "BadEmpanada",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "BadEmpanada is here, the political commentator is ready to debate and discuss.",
    "gender": "neutral",
    "react_as": "hostile",
    "armor": 4,
    "name_color": "g",
    "str": 17,
    "level": 8,
    "natural_weapon": {
        "name": "debate",
        "damage_type": "blunt",
        "damage": 24,
        "speed": 4,
        "energy_cost": 2,
    },
    "exp_reward": 9000,
    "can_attack": True,
}

Dream = {
    "typeclass": "typeclasses.characters.NPC",
    "key": "Dream",
    "aliases": ["human"],
    "tags": ["youtuber"],
    "desc": "Dream, the Minecraft speedrunner, is here, his mask hiding his true identity.",
    "gender": "male",
    "react_as": "friendly",
    "armor": 4,
    "name_color": "g",
    "str": 17,
    "level": 8,
    "natural_weapon": {
        "name": "sword",
        "damage_type": "edged",
        "damage": 24,
        "speed": 4,
        "energy_cost": 2,
    },
    "exp_reward": 12345,
    "can_attack": True,
}
