import math

from typeclasses.changelingguild.changeling_attack import ChangelingAttack

class Gecko(ChangelingAttack):
    """
    The tails of most geckos serve as nutrient stores, and
    are extremely fragile.  Often acting as decoys in a fight,
    the tails are regenerated by the gecko after several days.
    Tokay geckos are often sold in pet shops.
    """

    damage = 1
    energy_cost = 3
    skill = "blunt"
    name = "bite"
    speed = 3
    power = 5,
    toughness = 5,
    dodge = 5,

    def at_attack(self, wielder, target, **kwargs):
        """
        The auto attack Teiid
        """
        self.name = "bite"
        damage = 10 + self.db.guild_level + math.ceil(wielder.db.strength / 3)
        self.energy_cost = 1
        self.speed = 3
        self.emote = f"You bite viciously at $you(target), but miss entirely."
        self.emote_hit = f"You bite glancingly into $you(target), and cause some minor scratches"        
            
        # subtract the energy required to use this
        wielder.db.ep -= self.energy_cost
        target.at_damage(wielder, damage, "blunt")
        super().at_attack(wielder, target, **kwargs)
        wielder.msg(f"[ Cooldown: {self.speed} seconds ]")
        wielder.cooldowns.add("attack", self.speed)
        